"""Generate the small, deterministic BMP fixture and its firmware byte array."""
from pathlib import Path
import struct

root = Path(__file__).resolve().parent.parent
rows = [
    [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 255)],
    [(255, 255, 0), (0, 255, 255), (255, 0, 255), (0, 0, 0)],
]
width, height = 4, 2
pixels = bytes(channel for row in reversed(rows) for rgb in row for channel in reversed(rgb))
data = struct.pack('<2sIHHI', b'BM', 54 + len(pixels), 0, 0, 54)
data += struct.pack('<IiiHHIIiiII', 40, width, height, 1, 24, 0, len(pixels), 0, 0, 0, 0)
data += pixels
fixture = root / 'examples/media/test_bars.bmp'
fixture.parent.mkdir(parents=True, exist_ok=True)
fixture.write_bytes(data)
lines = [', '.join(f'0x{byte:02X}' for byte in data[i:i+12]) for i in range(0, len(data), 12)]
header = '#pragma once\n#include <cstdint>\n\nnamespace media {\n'
header += '// Generated by tools/generate-test-bmp.py; matches examples/media/test_bars.bmp.\n'
header += 'constexpr uint8_t kExampleBmp[] = {\n  ' + ',\n  '.join(lines) + '\n};\n'
header += '}  // namespace media\n'
(root / 'src/media/builtin_image.h').write_text(header, encoding='utf-8')
print(f'Generated {width}x{height} BMP and firmware fixture ({len(data)} bytes).')
