"""Create deterministic codec fixtures; requires Pillow (test generation only)."""
from pathlib import Path
import sys
import random

root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(root / '.build-temp/python-packages'))
from PIL import Image

out = root / 'examples/media'
out.mkdir(parents=True, exist_ok=True)
image = Image.new('RGB', (32, 16))
colors = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 255)]
image.putdata([colors[x // 8] for y in range(16) for x in range(32)])
image.save(out / 'test_bars.jpg', quality=95, subsampling=0, optimize=False, progressive=False)
image.save(out / 'test_progressive.jpg', quality=95, subsampling=0, progressive=True)
gray = Image.new('L', (7, 5), 128)
gray.save(out / 'test_gray.jpg', quality=95)
odd = Image.new('RGB', (17, 9), (40, 160, 220))
odd.save(out / 'test_420.jpg', quality=95, subsampling=2)
odd.save(out / 'test_422.jpg', quality=95, subsampling=1)
randomizer = random.Random(42)
noise = Image.frombytes('RGB', (128, 64), bytes(randomizer.randrange(256) for _ in range(128 * 64 * 3)))
noise.save(out / 'test_max.jpg', quality=95, subsampling=0)
oversize = Image.new('RGB', (129, 1), (255, 0, 0))
oversize.save(out / 'test_oversize.jpg', quality=95)
data = (out / 'test_bars.jpg').read_bytes()
lines = [', '.join(f'0x{byte:02X}' for byte in data[i:i+12]) for i in range(0, len(data), 12)]
header = '#pragma once\n#include <cstdint>\nnamespace media {\n'
header += '// Generated by tools/generate-test-jpeg.py.\nconstexpr uint8_t kExampleJpeg[] = {\n  '
header += ',\n  '.join(lines) + '\n};\n}  // namespace media\n'
(root / 'src/media/builtin_jpeg.h').write_text(header, encoding='utf-8')
print(f'Generated baseline/progressive/grayscale/4:2:0/oversize fixtures; builtin {len(data)} bytes.')
